FORMAT: 1A
HOST: #

# KR public API 

Polls is a simple API allowing consumers to view polls and vote in them.

## Token Create [/auth/token/create]

### Create a personal token to allow a user make private requistions [POST]

+ Response 200 (application/json)

    
        {
            "acess_token": "YEaskdhshdsaldkasdmasdas",
        }
    


## Token refresh [/auth/token/refresh]

### refresh a user personal token [POST]

+ Response 200 (application/json)

    
        {
            "acess_token": "YEaskdhshdsaldkasdmasdas",
            "refresh_token": "YEaskdhshdsaldkasdmasdas",
        }